### ISSUE TITLE
有两个疑问

### ISSUE THREAD

**Issue by kenser** [UJX6N/bbrplus-5.14#1]
1.lsmod|grep bbrplus怎么看不到，所以实际生效没有呢。
2.据说5.1以上版本的内核已经默认合并了bbrplus的特性，那是否直接用高版本内核自带的bbr就好了呢。

**Comment by UJX6N** [comment]
**第一个问题**
只有编译成mod【即在.config里`CONFIG_TCP_CONG_BBRPLUS=m`】，才会在lsmod里显示
如果编译进内核本体【即在.config里`CONFIG_TCP_CONG_BBRPLUS=y`】，就不会在lsmod显示，因为不是mod

要看是否生效，主要看
`sysctl net.ipv4.tcp_congestion_control`
如果显示是bbrplus就是生效了

**第二个问题**
其实bbr从4.19开始就没有太大修改，官方修改主要是修bug，但tcp传输本身的处理是有较大改进的，所以效果就见仁见智了，我觉得用高版本内核自带bbr也是可以的。这项目我主要移植着玩，效果我没怎么测试，只是我自己用着觉得也还行。

**Comment by kenser** [comment]
emm，听说是bbrplus的修改已经合并到bbr了不知道是不是真的，咱也不知道。那我暂且先用这个吧。多谢。
